### ISSUE TITLE
.NoClassDefFoundError issue

### ISSUE THREAD

**Issue by jojonarte** [Atmosphere/wasync#142]
I'm having issue with this.

```
 FATAL EXCEPTION: main
  Process: com.dnamicro.socketspike, PID: 17369
java.lang.NoClassDefFoundError: Failed resolution of: Lcom/ning/http/client/providers/netty/NettyAsyncHttpProviderConfig;
                                                                              at org.atmosphere.wasync.impl.ClientUtil.createDefaultAsyncHttpClient(ClientUtil.java:35)
                                                                              at org.atmosphere.wasync.impl.ClientUtil.create(ClientUtil.java:82)
                                                                              at org.atmosphere.wasync.impl.DefaultClient.create(DefaultClient.java:39)
                                                                              at com.dnamicro.socketspike.MainActivity.onCreate(MainActivity.java:53)
                                                                              at android.app.Activity.performCreate(Activity.java:5990)
                                                                              at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106)
                                                                              at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2278)
                                                                              at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387)
                                                                              at android.app.ActivityThread.access$800(ActivityThread.java:151)
                                                                              at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303)
                                                                              at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                              at android.os.Looper.loop(Looper.java:135)
                                                                              at android.app.ActivityThread.main(ActivityThread.java:5254)
                                                                              at java.lang.reflect.Method.invoke(Native Method)
                                                                              at java.lang.reflect.Method.invoke(Method.java:372)
                                                                              at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
                                                                              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
                                                                           Caused by: java.lang.ClassNotFoundException: Didn't find class "com.ning.http.client.providers.netty.NettyAsyncHttpProviderConfig" on path: DexPathList[[dex file "/data/data/com.dnamicro.socketspike/files/instant-run/dex/slice-wasync-2.1.2_54444329dc284f39a187c7bd1e04d769a521e165-classes.dex", dex file "/data/data/com.dnamicro.socketspike/files/instant-run/dex/slice-support-annotations-25.0.0_820d30748544d402162c2f05b7be91a897b34685-classes.dex", dex file "/data/data/com.dnamicro.socketspike/files/instant-run/dex/slice-slice_9-classes.dex", dex file "/data/data/com.dnamicro.socketspike/files/instant-run/dex/slice-slice_8-classes.dex", dex file "/data/data/com.dnamicro.socketspike/files/instant-run/dex/slice-slice_7-classes.dex", dex file "/data/data/com.dnamicro.socketspike/files/instant-run/dex/slice-slice_6-classes.dex", dex file "/data/data/com.dnamicro.socketspike/files/instant-run/dex/slice-slice_5-classes.dex", dex file "/data/data/com.dnamicro.socketspike/files/instant-run/dex/slice-slice_4-classes.dex", dex file "/data/data/com.dnamicro.socketspike/files/instant-run/dex/slice-slice_3-classes.dex", dex file "/data/data/com.dnamicro.socketspike/files/instant-run/dex/slice-slice_2-classes.dex", dex file "/data/data/com.dnamicro.socketspike/files/instant-run/dex/slice-slice_1-classes.dex", dex file "/data/data/com.dnamicro.socketspike/files/instant-run/dex/slice-slice_0-classes.dex", dex file "/data/data/com.dnamicro.socketspike/files/instant-run/dex/slice-internal_impl-25.0.0_cfc271e71cf242a894aa2bd7c43fe9b0700deb9e-classes.dex", dex file "/data/data/com.dnamicro.socketspike/files/instant-run/dex/slice-internal_impl-25.0.0_9b2262db8bf85ac405dbfd0761993c3cc25d2925-classes.dex", dex file "/data/data/com.dnamicro.socketspike/files/instant-run/dex/slice-internal_impl-25.0.0_7498622be1272cbe9e92fe4575cafb0fe30b90b5-classes.dex", dex file "/data/data/com.dnamicro.socketspike/files/instant-run/dex/slice-internal_impl-25.0.0_70c6edc7dc1127769247ea6af150793e1e23add9-classes.dex", dex file "/data/data/com.dnamicro.socketspike/files/instant-run/dex/slice-internal_impl-25.0.0_2064f411c728f10c3e1925d1206fb87556fd6a63-classes.dex", dex file "/data/data/com.dnamicro.socketspike/files/instant-run/dex/slice-com.android.support-support-vector-drawable-25.0.0_22af9ec887fdda3f7e88cad5ef9715de4bcd9b2f-classes.dex", dex file "/data/data/com.dnamicro.socketspike/files/instant-run/dex/slice-com.android.support-support-v4-25.0.0_8548e9ea250dff2b0c646fe78d8b75fa9e63f020-classes.dex", dex file "/data/data/com.dnamicro.socketspike/files/instant-run/dex/slice-com.android.support-support-media-compat-25.0.0_83dbad36fe0da59807124b734e7a3bfa482fb931-classes.dex", dex file "/data/data/com
com.dnamicro.socketspike D/Error: ERR: exClass=java.lang.ClassNotFoundException
com.dnamicro.socketspike D/Error: ERR: exMsg=Didn't find class "com.ning.http.client.providers.netty.NettyAsyncHttpProviderConfig" on path: DexPathList[[dex file "/data/data/com.dnamicro.socketspike/files/instant-run/dex/slice-wasync-2.1.2_54444329dc284f39a187c7bd1e04d769a521e165-classes.dex", dex file "/data/data/com.dnamicro.socketspike/files/instant-run/dex/slice-support-annotations-25.0.0_820d30748544d402162c2f05b7be91a897b34685-classes.dex", dex file "/data/data/com.dnamicro.socketspike/files/instant-run/dex/slice-slice_9-classes.dex", dex file "/data/data/com.dnamicro.socketspike/files/instant-run/dex/slice-slice_8-classes.dex", dex file "/data/data/com.dnamicro.socketspike/files/instant-run/dex/slice-slice_7-classes.dex", dex file "/data/data/com.dnamicro.socketspike/files/instant-run/dex/slice-slice_6-classes.dex", dex file "/data/data/com.dnamicro.socketspike/files/instant-run/dex/slice-slice_5-classes.dex", dex file "/data/data/com.dnamicro.socketspike/files/instant-run/dex/slice-slice_4-classes.dex", dex file "/data/data/com.dnamicro.socketspike/files/instant-run/dex/slice-slice_3-classes.dex", dex file "/data/data/com.dnamicro.socketspike/files/instant-run/dex/slice-slice_2-classes.dex", dex file "/data/data/com.dnamicro.socketspike/files/instant-run/dex/slice-slice_1-classes.dex", dex file "/data/data/com.dnamicro.socketspike/files/instant-run/dex/slice-slice_0-classes.dex", dex file "/data/data/com.dnamicro.socketspike/files/instant-run/dex/slice-internal_impl-25.0.0_cfc271e71cf242a894aa2bd7c43fe9b0700deb9e-classes.dex", dex file "/data/data/com.dnamicro.socketspike/files/instant-run/dex/slice-internal_impl-25.0.0_9b2262db8bf85ac405dbfd0761993c3cc25d2925-classes.dex", dex file "/data/data/com.dnamicro.socketspike/files/instant-run/dex/slice-internal_impl-25.0.0_7498622be1272cbe9e92fe4575cafb0fe30b90b5-classes.dex", dex file "/data/data/com.dnamicro.socketspike/files/instant-run/dex/slice-internal_impl-25.0.0_70c6edc7dc1127769247ea6af150793e1e23add9-classes.dex", dex file "/data/data/com.dnamicro.socketspike/files/instant-run/dex/slice-internal_impl-25.0.0_2064f411c728f10c3e1925d1206fb87556fd6a63-classes.dex", dex file "/data/data/com.dnamicro.socketspike/files/instant-run/dex/slice-com.android.support-support-vector-drawable-25.0.0_22af9ec887fdda3f7e88cad5ef9715de4bcd9b2f-classes.dex", dex file "/data/data/com.dnamicro.socketspike/files/instant-run/dex/slice-com.android.support-support-v4-25.0.0_8548e9ea250dff2b0c646fe78d8b75fa9e63f020-classes.dex", dex file "/data/data/com.dnamicro.socketspike/files/instant-run/dex/slice-com.android.support-support-media-compat-25.0.0_83dbad36fe0da59807124b734e7a3bfa482fb931-classes.dex", dex file "/data/data/com.dnamicro.socketspike/files/instant-run/dex/slice-com.android.support-support-fragment-25.0.0_d8c13d89336ba8c2ab5a4db9c56ff989bcf63a56-classes.dex", dex file "/data/data/com.dnamicro.socketspike/files/instant-run/dex/slice-com.android.support-support-core-utils-25.0.0_e2d7a7b97618aaaaff9ef80b57b00686ba67b817-classes.dex", dex file "/data/data/com.dnamicro.socketspike/files/instant-run/dex/slice-com.android.support-support-core-ui-25.0.0_4038d681057654882a9335daf1b6464e790356ff-classes.dex", dex file "/data/data/com.dnamicro.socketspike/files/instant-run/dex/slice-com.android.support-support-compat-25.0.0_2f36e6a0f3ffc783abe148b9d2fed26a19631888-classes.dex", dex file "/data/data/com.dnamicro.socketspike/files/instant-run/dex/slice-com.android.support-appcompat-v7-25.0.0_4eece7bf0786f9592f9785454015cd51fb570042-classes.dex", dex file "/data/data/com.dnamicro.socketspike/files/instant-run/dex/slice-com.android.support-animated-vector-drawable-25.0.0_3e9f5be5a5265dcd18d0fd48ba14677a5b4b1da4-classes.dex"],nativeLibraryDirectories=[/vendor/lib, /system/lib, /vendor/lib, /system/lib]]
com.dnamicro.socketspike D/Error: ERR: file=BaseDexClassLoader.java
com.dnamicro.socketspike D/Error: ERR: class=dalvik.system.BaseDexClassLoader
com.dnamicro.socketspike D/Error: ERR: method=findClass line=56
com.dnamicro.socketspike D/Error: ERR: stack=java.lang.NoClassDefFoundError: Failed resolution of: Lcom/ning/http/client/providers/netty/NettyAsyncHttpProviderConfig;
                                                                     at org.atmosphere.wasync.impl.ClientUtil.createDefaultAsyncHttpClient(ClientUtil.java:35)
                                                                     at org.atmosphere.wasync.impl.ClientUtil.create(ClientUtil.java:82)
                                                                     at org.atmosphere.wasync.impl.DefaultClient.create(DefaultClient.java:39)
                                                                     at com.dnamicro.socketspike.MainActivity.onCreate(MainActivity.java:53)
                                                                     at android.app.Activity.performCreate(Activity.java:5990)
                                                                     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106)
                                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2278)
                                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387)
                                                                     at android.app.ActivityThread.access$800(ActivityThread.java:151)
                                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303)
                                                                     at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                     at android.os.Looper.loop(Looper.java:135)
                                                                     at android.app.ActivityThread.main(ActivityThread.java:5254)
                                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                                     at java.lang.reflect.Method.invoke(Method.java:372)
                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
                                                                  Caused by: java.lang.ClassNotFoundException: Didn't find class "com.ning.http.client.providers.netty.NettyAsyncHttpProviderConfig" on path: DexPathList[[dex file "/data/data/com.dnamicro.socketspike/files/instant-run/dex/slice-wasync-2.1.2_54444329dc284f39a187c7bd1e04d769a521e165-classes.dex", dex file "/data/data/com.dnamicro.socketspike/files/instant-run/dex/slice-support-annotations-25.0.0_820d30748544d402162c2f05b7be91a897b34685-classes.dex", dex file "/data/data/com.dnamicro.socketspike/files/instant-run/dex/slice-slice_9-classes.dex", dex file "/data/data/com.dnamicro.socketspike/files/instant-run/dex/slice-slice_8-classes.dex", dex file "/data/data/com.dnamicro.socketspike/files/instant-run/dex/slice-slice_7-classes.dex", dex file "/data/data/com.dnamicro.socketspike/files/instant-run/dex/slice-slice_6-classes.dex", dex file "/data/data/com.dnamicro.socketspike/files/instant-run/dex/slice-slice_5-classes.dex", dex file "/data/data/com.dnamicro.socketspike/files/instant-run/dex/slice-slice_4-classes.dex", dex file "/data/data/com.dnamicro.socketspike/files/instant-run/dex/slice-slice_3-classes.dex", dex file "/data/data/com.dnamicro.socketspike/files/instant-run/dex/slice-slice_2-classes.dex", dex file "/data/data/com.dnamicro.socketspike/files/instant-run/dex/slice-slice_1-classes.dex", dex file "/data/data/com.dnamicro.socketspike/files/instant-run/dex/slice-slice_0-classes.dex", dex file "/data/data/com.dnamicro.socketspike/files/instant-run/dex/slice-internal_impl-25.0.0_cfc271e71cf242a894aa2bd7c43fe9b0700deb9e-classes.dex", dex file "/data/data/com.dnamicro.socketspike/files/instant-run/dex/slice-internal_impl-25.0.0_9b2262db8bf85ac405dbfd0761993c3cc25d2925-classes.dex", dex file "/data/data/com.dnamicro.socketspike/files/instant-run/dex/slice-internal_impl-25.0.0_7498622be1272cbe9e92fe4575cafb0fe30b90b5-classes.dex", dex file "/data/data/com.dnamicro.socketspike/files/instant-run/dex/slice-internal_impl-25.0.0_70c6edc7dc1127769247ea6af150793e1e23add9-classes.dex", dex file "/data/data/com.dnamicro.socketspike/files/instant-run/dex/slice-internal_impl-25.0.0_2064f411c728f10c3e1925d1206fb87556fd6a63-classes.dex", dex file "/data/data/com.dnamicro.socketspike/files/instant-run/dex/slice-com.android.support-support-vector-drawable-25.0.0_22af9ec887fdda3f7e88cad5ef9715de4bcd9b2f-classes.dex", dex file "/data/data/com.dnamicro.socketspike/files/instant-run/dex/slice-com.android.support-support-v4-25.0.0_8548e9ea250dff2b0c646fe78d8b75fa9e63f020-classes.dex", dex file "/data/data/com.dnamicro.socketspike/files/instant-run/dex/slice-com.android.support-support-media-compat-25.0.0_83dbad36fe0da59807124b734e7a3bfa482fb931-classes.dex", dex file "/data/data/com.dnamicro.socketspike/files/instant-run/dex/slice-com.android.supp
com.dnamicro.socketspike D/Error: ERR: TOTAL BYTES WRITTEN: 28968

```

**Comment by thabach** [comment]
@jojonarte please consult https://github.com/AsyncHttpClient/async-http-client/issues/849
