### ISSUE TITLE
java.lang.VerifyError for Android API Level < 21 with wasync Version 2.1.3

### ISSUE THREAD

**Issue by phillippbertram** [Atmosphere/wasync#143]
Hi there!

I am using wasync 2.3.1 in my current Project and everything worked fine till I tried my app on an API-Level < 21. 
My app crashes when creating the socket from the client because of an `java.lang.VerifyError` for `JDKAsyncHttpProvider`. 

**Example Code:**

```java
AtmosphereClient client = ClientFactory.getDefault().newClient(AtmosphereClient.class);

RequestBuilder request = client.newRequestBuilder()
        .method(Request.METHOD.GET)
        .uri("" + "/suspend")
        .trackMessageLength(true)
        .transport(Request.TRANSPORT.LONG_POLLING);


Socket socket = client.create(); // <--- here it crashes!!!

try {
    socket.on(new Function<Reader>() {
        @Override
        public void on(Reader r) {
            // Read the response
            Log.d("WebSocket", "response");
        }
    }).on(new Function<IOException>() {

        @Override
        public void on(IOException ioe) {
            // Some IOException occurred
            Log.d("WebSocket", "IOException");
        }

    }).open(request.build()).fire("echo").fire("bong");
} catch (IOException e) {
    e.printStackTrace();
}
```

I also tried many other `Client` implementations, but always with the same result.

I get following stacktrace:

```console
java.lang.VerifyError: com/ning/http/client/providers/jdk/JDKAsyncHttpProvider
                       at com.ning.http.client.AsyncHttpClient.loadDefaultProvider(AsyncHttpClient.java:591)
                       at com.ning.http.client.AsyncHttpClient.<init>(AsyncHttpClient.java:187)
                       at org.atmosphere.wasync.impl.ClientUtil.createDefaultAsyncHttpClient(ClientUtil.java:51)
                       at org.atmosphere.wasync.impl.ClientUtil.createDefaultAsyncHttpClient(ClientUtil.java:38)
                       at org.atmosphere.wasync.impl.ClientUtil.create(ClientUtil.java:76)
                       at org.atmosphere.wasync.impl.AtmosphereClient.create(AtmosphereClient.java:41)
                       at ...
```

After unsuccessfully reading several threads and wasting much time, I just downgraded wasync to 2.1.2 and the error was gone.

Furthermore the problem seems to have nothing to do with following multidexing or retrolamda.

**Comment by erobic** [comment]
I am facing exactly same problems. Have you guys found out the solution?

**Comment by phillippbertram** [comment]
Unfortunately no 😢 

We just used Version 1.4.3 because it was the most stable one for our API Level range.
We could handle the `java.io.IOException: Remotely Closed` Exception, because it was just thrown because of an self signed certificate on server side.

I am still waiting for any feedback 🙄

**Comment by ricardojlrufino** [comment]
I think the supported minimum should be API 19

**Comment by shubhamrai1993** [comment]
The API support level should  be written somewhere upfront.
